scale = "Get this by running Packet Capture on your Android phone"
userId = "Same as scale value"
code = "Get this by running Packet Capture on your Android phone"
token = "Get this by running Packet Capture on your Android phone"
useGSheets = false
gSheetsId = "Get it from the part of the url after /d/ in the Google Sheet you want to use"
gSheetsTabId = "Get it from the gid in url of the Google Sheet you want to use"
